### ISSUE TITLE
Import/Export for Permissions

### ISSUE THREAD

**Issue by Croshadow123** [fusionjack/Adhell3#10]
Could we get the same option for Permissions too? (Import to Storage/Export from Storage). I have disabled permissions for some apps, would hate if something happens and i need to do it again.

**Comment by Croshadow123** [comment]
If this makes any sense to make the options for Permissions too!?

**Comment by fusionjack** [comment]
I plan to add backup/restore functionality for the whole app.
So, there will be only one file that has all user's settings, e.g. package disabler, mobile restricter, permissions, custom providers, etc.
Please wait for this feature :)
