### ISSUE TITLE
Question of license

### ISSUE THREAD

**Issue by mehtadone** [fusionjack/Adhell3#11]
Hi,

Sorry this isn't an issue but didn't know where to put it. 

Which license key do you need to put into the app? I've tried both keys but get an invalid license toast.

Thanks

**Comment by herexf** [comment]
What's the first 5 characters you got from Samsung?
If the key begins with letters "KLM", it's incorrect.

Should be Enterprise license key under KNOX standard SDK

**Comment by mehtadone** [comment]
I have a License Key that begins KLM and a
ELM License Key which is huge. Neither work. Maybe it's because I didn't sign up as an organisation and only a dev

**Comment by Mike-BITW** [comment]
You need a valid current **128-byte Legacy Knox Standard SDK Enterprise license key.**

**Comment by herexf** [comment]
ELM key should be fine, mine is ELM as well, no org information, did you get any errors? How many packages you have already activated, different package name, please be advised that they key can be only activated for less than 10 packages and will be expried after 90 days.

**Comment by fusionjack** [comment]
Added to README how to generate license key.

**Comment by mehtadone** [comment]
Thank was it. I needed legacy. Appreciate the help
