### ISSUE TITLE
Chrome app on port 53 

### ISSUE THREAD

**Issue by binoandroid** [fusionjack/Adhell3#14]
Everything works fine on galaxy s7.
There is no option for pot 53.

**Comment by OsamaNasser** [comment]
Go to block custom url and add the following line
com.android.chrome|*|53

**Comment by Mike-BITW** [comment]
See README.md under "Custom deny firewall rule".

Another (better?) approach is to simply disable Chrome's aggressive "_Async DNS_" option under **chrome://flags** (or to use another browser...). ;)

**Comment by binoandroid** [comment]
Thanks to **OsamaNasser** I solved it.
