### ISSUE TITLE
DNS Problem

### ISSUE THREAD

**Issue by mertcelen** [fusionjack/Adhell3#15]
Problem : DNS prevents Google Play to download any updates, installations. I tried many dns providers but none of them works.

**Comment by Mike-BITW** [comment]
This had been reported in various AdHell/SABS threads.  It seems to depend a lot on specific configurations (location, ISP, et.).  For me, as an example, Google's DNS didn't interfere with the Play Store but forced me to use the IP for my MMS server (in the APN) to be able to send MMS.  This doesn't seem to be anything over which AdHell3 has any control

**Comment by mertcelen** [comment]
Thanks for quick response, is there any way that you can whitelist Google Play from DNS?

**Comment by Mike-BITW** [comment]
Not that I know of, but think carefully about how badly you need to switch DNS on your phone.  In fact, some ISPs completely disregard your settings and intercept all DNS calls.

**Comment by mertcelen** [comment]
Well, I live in Turkey. İ think you will understand why I need that. Thanks anyways for help. Please close this issue after you read this

**Comment by Mike-BITW** [comment]
Sometimes, a VPN is actually preferable in your situation.  At least you should be able to benefit from many of the AdHell3 features, with or without DNS. Good luck to you!

(I can't close your issue, this is @fusionjack's repo, not mine)

**Comment by mertcelen** [comment]
Just think about having VPN all the time, and my country is currently consider VPN as issue and they are blocking it right now. Anyways I'm closing now, thanks for help

**Comment by fusionjack** [comment]
i'll take a look the code if i have time
