### ISSUE TITLE
Looks app will update all hosts even not checked.

### ISSUE THREAD

**Issue by herexf** [fusionjack/Adhell3#16]
Hello

Me again, I have added multiple testing hosts files, looks the app will update all files even the hosts isn't checked.

Thanks

**Comment by fusionjack** [comment]
yes, that is at least the current behavior.
with 15000 limit, one host source could alone exceeds this limit and when you check the chekbox of this host source, it will be unchecked because it contains more than 15000.
if we only update the checked ones, this source cannot be updated at all.

**Comment by herexf** [comment]
Got it, I assumed you have moved the checked hosts to the database, so all the unchecked hosts should be removed from the database immediately once we unchecked the hosts.

Anyway, thanks for your reply.

**Comment by fusionjack** [comment]
Yes, when a provider in unchecked, its domains list are removed from database. When it is checked, it will be added to database.
But, when you update all providers, their domains will be added to database even for not unchecked one. This is redundant which I'll change.
I'll close this as this is current behavior. It might change if I implement more changes related to the limit.
