### ISSUE TITLE
Whitelist URL for a specific app = whitelisting the app?

### ISSUE THREAD

**Issue by Chinchilla-white** [fusionjack/Adhell3#20]
It seems that whitelising URL for a specific app doesn't work, and effectively this works just as whitelisting the app.

I blocked the domain graph.facebook.com system wide, and whitelised the URL for Facebook lite : com.facebook.lite|graph.facebook.com, all the other URL wasn't blocked either for facebook lite.

**Comment by fusionjack** [comment]
graph.facebook.com is not blocking fb ads. it is just fb API.
blocking fb ads is just as hard as blocking youtube ads. sometimes ads are showing up sometimes not.
fb lite doesn't use graph.facebook.com for login. you don't need to whitelist it.
fb messenger for example, use graph.facebook.com to login.

and no, "whitelist url for app" is not the same with "whitelist app"
don't forget to turn off and turn on adhell when you whitelist url.

**Comment by fusionjack** [comment]
Apparently, you are right. This is a bug.
I have fix this in this following commit: https://github.com/fusionjack/Adhell3/commit/bf61fe67c15ccb366f3e734528ef7444e50ca3e1

Thanks for reporting this.
Please try it and reopen if this still doesn't work.

**Comment by Chinchilla-white** [comment]
Thanks!


On 3 April 2018 at 11:10:41 PM, Chandra Poerwanto (notifications@github.com)
wrote:

Apparently, you are right. This is a bug.
I have fix this in this following commit: bf61fe6
<https://github.com/fusionjack/Adhell3/commit/bf61fe67c15ccb366f3e734528ef7444e50ca3e1>

Thanks for reporting this.
Please try it and reopen if this still doesn't work.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/fusionjack/Adhell3/issues/20#issuecomment-378284894>,
or mute the thread

**Comment by Chinchilla-white** [comment]
Cannot turn on Adhell3 with the latest build.  Stuck at enabling ….


On 3 April 2018 at 11:28:04 PM, Francisco Wong (wonghyf@gmail.com) wrote:

Thanks!


On 3 April 2018 at 11:10:41 PM, Chandra Poerwanto (notifications@github.com)
wrote:

Apparently, you are right. This is a bug.
I have fix this in this following commit: bf61fe6
<https://github.com/fusionjack/Adhell3/commit/bf61fe67c15ccb366f3e734528ef7444e50ca3e1>

Thanks for reporting this.
Please try it and reopen if this still doesn't work.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/fusionjack/Adhell3/issues/20#issuecomment-378284894>,
or mute the thread

**Comment by fusionjack** [comment]
it took now longer to enable because for every whitelist url rule, the whole blocked domains need to be added.
it depends now how many whitelist rules you have.
adding the whole domains with default host list took around 1-2 minutes. if you have 10 whitelist rules, it multiples.
check also the adhell_log.txt when it finished enabling.
enabling/disabling adhell is still working on my side.
