### ISSUE TITLE
Cannot active License

### ISSUE THREAD

**Issue by anhdq00317** [fusionjack/Adhell3#26]
Cannot active License, always get error "License active failed: Unknown"

**Comment by Croshadow123** [comment]
Maybe you got the wrong knox key or he expired.

**Comment by anhdq00317** [comment]
I used Knox SDK "Enterprise license key", I also tried with new created key but still the same error "License activation failed: Unknown"

**Comment by anhdq00317** [comment]
With latest code, I did not get this issue anymore. Thanks
