### ISSUE TITLE
time in report

### ISSUE THREAD

**Issue by khasttj92** [fusionjack/Adhell3#5]
time in report no proper in one line. I'm using j7 2015. Here the link of picture.
http://i.imgur.com/rMrqfHJ.jpg

**Comment by fusionjack** [comment]
could you check which android API you are using?
i'll fix the layout anyway. thanks for reporting.

**Comment by khasttj92** [comment]
your welcome and thanks. API 23 android m

**Comment by fusionjack** [comment]
how about the custom provider layout? is that ok? could you attach a screenshot?

**Comment by herexf** [comment]
Another issue,

Adhell keeps stopping after I added a local hosts file, not sure it's caused by some special characters or too many lines, about 70000 lines, but it works before..

**Comment by khasttj92** [comment]
the rest are ok but here the link attach.
http://imgur.com/mFqcMxg
http://imgur.com/gfbjHAB
http://imgur.com/eY2rrwO

**Comment by fusionjack** [comment]
@khasttj92: what i meant is this one https://imgur.com/a/LQYqn

**Comment by fusionjack** [comment]
@herexf: please create a new issue, don't mix it here

**Comment by khasttj92** [comment]
doesnt have that one.

**Comment by khasttj92** [comment]
here the link. I install at other phone it has that  custom provider layout but in j7 2015 doesnt have.
http://i.imgur.com/5mliUMj.jpg

**Comment by fusionjack** [comment]
that is pretty strange. probably the button is overlapped. i'll check it.

**Comment by Croshadow123** [comment]
Okay.. you update the app thats why.. now i did the same and have the same icons

**Comment by fusionjack** [comment]
I did some changes on some layouts. Please rebuild the app with the latest commits and let me know about the result.

**Comment by khasttj92** [comment]
the time in report has fixed but still doesnt have custom provider. here the link.
http://imgur.com/HDhxyXb
http://imgur.com/gXBspyl

**Comment by fusionjack** [comment]
that is really strange. what language do you use in your phone?

**Comment by khasttj92** [comment]
english

**Comment by fusionjack** [comment]
ok, then currently i have no idea why it doesn't show up on your phone.
i believe you also don't have "change dns" button as i saw in your last screenshot: https://imgur.com/a/KN7C9
i'll change the layout anyway, perhaps it'll help.

**Comment by khasttj92** [comment]
yes change dns also doesnt have but it ok for me. mybe because the version of knox are to old. im use it at j7 2015 which mean 3 years old now. Btw thanks for help.

**Comment by fusionjack** [comment]
no problem, you basically don't have the third button in both layout and i have no idea why. i'll check the code again later, perhaps i miss something.

**Comment by khasttj92** [comment]
sure..👍

**Comment by fusionjack** [comment]
Solved the mystery!
Get the latest commit and you should see DNS and Custom Provider buttons.
