### ISSUE TITLE
Build 369 keeps stopping

### ISSUE THREAD

**Issue by herexf** [fusionjack/Adhell3#6]
Hello

Build 369 keeps stopping, I installed again without any local and remote hosts.
Disabled excel/word/MS point/game* and fb*.

Then cannot open adhell after around 1-2 mins.

I installed back to build 365, working well.

Thanks

**Comment by herexf** [comment]
Looks it's my issue. 
Don't know the reason.

**Comment by fusionjack** [comment]
Why you closed the issue if you still have question? :)

**Comment by fusionjack** [comment]
I assume build 365 is with this commit d00cc49aabc3977ec3a1ba8be805efa194ccb335?
That is the last database structure changes.
Try this:
* Uninstall the app
* Delete folder "adhell3" on your internal storage
* Install the app again

If you still have FC when opening the app, connect your phone with Android Studio and see the logcat. Paste here the exception.

**Comment by herexf** [comment]
Thanks,
Because I upgraded my system this evening, should be my issues because build 365 worked all day. 
I deleted the folder and all good now.

Cheers
