### ISSUE TITLE
Mobile restricter enabling all apps again

### ISSUE THREAD

**Issue by Croshadow123** [fusionjack/Adhell3#8]
I found one issuse. Every time when i install a new build (over Android Studio).. the Mobile restricter and the apps that i disabled are enabled again. Yeah i can easily tap the three dots and Import from Storage, its not a problem for me but maybe its a bug and u can fix it. Everything else (package disabler,permissions,custom providers) stay the same, only mobile restricter not.

**Comment by fusionjack** [comment]
yeah, i also noticed this issue.
one of the trigger is when you refresh the package disabler. the mobile apps setting will be reset. other triggers are still unclear.
i'll fix it together when i rework the mobile restricter.
today, i already reworked the package disabler. time to rest :relaxed:

**Comment by fusionjack** [comment]
It should be fixed now.
Re-import restricted apps from storage and do a refresh (pull-down). The restricted apps should be still there.
